update model evalaution21

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -34,16 +34,14 @@ jobs:
         git config --global user.email "github-actions@github.com"
         git config --global user.name "GitHub Actions"
 
-    - name: Configure DVC remote
+    - name: Verify and Configure DVC remote
       env:
         DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
       run: |
-        # Check if the 'origin' remote exists in DVC config
         if ! dvc remote list | grep -q "^origin"; then
           echo "Adding DVC remote 'origin'"
           dvc remote add origin https://dagshub.com/Shahbaz894/mloops-smProject.dvc
         fi
-        # Set authentication for the DVC remote
         dvc remote modify --local origin auth basic
         dvc remote modify --local origin user ${{ secrets.MLFLOW_TRACKING_USERNAME }}
         dvc remote modify --local origin password ${{ secrets.DAGSHUB_PAT }}
@@ -55,7 +53,7 @@ jobs:
         MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
         MLFLOW_TRACKING_URI: https://dagshub.com/Shahbaz894/mloops-smProject.mlflow
       run: |
-        dvc pull
+        dvc pull || echo "DVC pull failed. Check that files are in remote storage."
         dvc repro -v
         dvc push
 
